### ISSUE TITLE
How to turn off the odd line numbering

### ISSUE THREAD

**Issue by sindhus** [liangxianzhe/oh-my-vim#18]
I notice that when I used the arrow keys or j k to move up and down the text file the line numbering seems to change in reverse order making the currently focused line as the last line number and everything above the current line have numbering in reverse order. How can I turn this off? Thanks!

**Comment by etiennebatise** [comment]
I'd recommend you to read this http://vim.wikia.com/wiki/Display_line_numbers

At first, the _relative number_  option seems odd but in fact it is far more useful than not having it. This configuration lets you see you current line number and the relative line number let you move in the file easily. 

For example, if you have an error at compilation time with a C program or if Apache yells at you because you've made a mistake in a file, those tools will generally give you the line, let's say `42`. So in the file you can jump to that point with `42G` in `normal` mode.

Then you understand you mistake and  correct it. But you're noticing something's wrong few lines above, like 10-20. It would be really painful to count the lines or to take the mouse and click on it. So here is where _relative numbers_ are cool. You just know precisely that what you're noticing is exactly 14 lines above. So you type `14k` in `normal` mode and you're there easy. 

Hope I'm clear =)

**Comment by sindhus** [comment]
Thank you for the explanation, i can now see why its useful! :)

at the moment I am using vim to learn some nodes programming and nodejs tells me the line number where it couldn't compile. So how do I turn off and on relative line numbering should I want to?

**Comment by etiennebatise** [comment]
Maybe you could add a shortcut.

This is a very good article presenting a function o toggle _relative numbers_. It is very simple a complete my explanation. 

http://jeffkreeftmeijer.com/2012/relative-line-numbers-in-vim-for-super-fast-movement/

**Comment by sindhus** [comment]
am sure it is useful in certain contexts but i don't need it at the moment. can you please tell me how to disable it?

**Comment by etiennebatise** [comment]
The answer is here https://github.com/liangxianzhe/oh-my-vim/issues/11

**Comment by liangxianzhe** [comment]
Thanks @etiennebatise for the explanation!
